repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-json
      -   id: check-yaml
  -   repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
      - id: black
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      - id: flake8
