# Development venv for dinosar development
name: dinosar-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - msgpack-python<1
  - poetry=1.0
  - geopandas=0.7
  - cartopy=0.17
  - pip=20.0
  - pip:
    - poetry-dynamic-versioning~=0.5
