# Development venv for dinosar development
name: dinosar-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - poetry=1.0
  - geopandas
  - cartopy
  - pip=20.0
  - pip:
    - poetry-dynamic-versioning~=0.5
