name: isce2-dinosar
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.2
  - jupyterhub=1.1
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - isce2=2.3
  - geopandas=0.6
  - geoviews=1.6
  - datashader=0.10
  - hvplot=0.5
  - xarray=0.15
  - rasterio=1.1
  - pip=20.0
  - pip:
    - git+https://github.com/scottyhq/dinosar.git@master
