name: Conda-Build

on:
  pull_request:
    branches: master

jobs:
  conda:
    name: ${{ matrix.os }}-${{ matrix.CONDA_ENV }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        CONDA_ENV: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
           environment-file: ci/environment-dev-py${{ matrix.CONDA_ENV }}.yml
           activate-environment: dinosar
           miniconda-version: 4.7.12

      - name: Install Dinosar
        shell: bash -l {0}
        run: |
          conda --version
          python -m pip install --no-deps .
          conda list

      - name: Run PyTest
        shell: bash -l {0}
        run: |
          pytest --verbose --cov=dinosar --cov-config
