name: Conda-Build

on:
  pull_request:
    branches: master

jobs:
  conda:
    name: ${{ matrix.os }}-${{ matrix.CONDA_ENV }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        CONDA_ENV: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
           environment-file: ci/environment-dev-${{ matrix.CONDA_ENV }}.yml
           activate-environment: dinosar
        shell: bash -l {0}
        run: |
          conda --version
          python -m pip install --no-deps -e .
          conda list

      - name: Running Tests
        shell: bash -l {0}
        run: |
          pytest --verbose --cov=dinosar --cov-config
